services:
  coin-exchange-mysql:
    image: mysql:8.0
    container_name: coin-exchange-mysql
    ports:
      - "3302:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coinExchange
      MYSQL_TIMEZONE: Asia/Seoul
      LANG: ko_KR.UTF-8
    restart: always
    command: --default-time-zone='+09:00'

  coin-exchange-rabbitmq:
    image: rabbitmq:3-management
    container_name: coin-exchange-rabbitmq
    ports:
      - "5673:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  coin-exchange-prometheus:
    image: prom/prometheus:latest
    container_name: coin-exchange-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  coin-exchange-grafana:
    image: grafana/grafana:latest
    container_name: coin-exchange-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: 1234
    depends_on:
      - coin-exchange-prometheus
    restart: always

  coin-exchange-redis:
    image: redis:7.2
    container_name: coin-exchange-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
