rootProject.name = 'coinExchange'

include 'app-funds'
include 'app-trading'
include 'app-projection'
include 'gateway'
include 'events-contract'
include 'common-core'
include 'common-jpa'
include 'common-auth'
include 'infra-notification'
include 'domain-coin'
include 'domain-user'
include 'domain-deposit'
include 'domain-withdraw'
include 'domain-trade'
include 'domain-order'
include 'domain-matching'
include 'domain-wallet'
