spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://coin-exchange-user:8082
          predicates:
            - Path=/api/users/**
        - id: trading-service
          uri: http://coin-exchange-trading:8084
          predicates:
            - Path=/api/orders/**,/api/trades/**
        - id: funds-service
          uri: http://coin-exchange-funds:8083
          predicates:
            - Path=/api/wallets/**,/api/deposits/**,/api/withdraws/**,/admin/deposits/**,/admin/withdraws/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
